/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import java.awt.Dimension;
import javax.swing.JPanel;
import javax.swing.JTextField;
import java.awt.Color;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author velasam
 */
public class Tablero extends javax.swing.JFrame {
    private int tiempo, numbombs, anis, tiem;
    private int bombs[][];
    private Animat ani[];
    private JTextField grid[][];

    /**
     * Creates new form Tablero
     */
    public Tablero(int r, int c, int anis, int maxT) {
        tiempo = maxT;
        tiem = 0;
        ani = new Animat[anis];
        grid = new JTextField[r][c];
        this.anis = anis;
        double ancho, alto;
        ancho = 230/c;
        alto = 230/r;
        JPanel myPanel = (JPanel)this.getContentPane();
        myPanel.setLayout(null);
        Dimension d = new Dimension();
        initComponents();
        //Creación del grid
        for (int i = 0; i < r; i++) {
            for (int j = 0; j < c; j++) {
                grid[i][j] = new JTextField("");
                grid[i][j].setEditable(false);
                d.setSize(ancho, alto);
                grid[i][j].setBounds((int)(j*ancho)+25, (int)(i*alto)+65, (int)ancho, (int)alto);
                myPanel.add(grid[i][j]);
                if (i%2 != 0 && j%2 != 0)
                    grid[i][j].setBackground(Color.BLACK);
            }
        }
        //Creación y colocación bombas
        Random rand = new Random();
        numbombs = rand.nextInt((int)Math.floor(0.3*r*c));
        if (numbombs == 0)
            numbombs++;
        jLabel4.setText(numbombs + "");
        bombs = new int[numbombs][2];
        for (int i = 0; i < numbombs; i++) {
            bombs[i][0] = rand.nextInt(r);
            bombs[i][1] = rand.nextInt(c);
            while (bombs[i][0]%2 != 0 && bombs[i][1]%2 != 0 || grid[bombs[i][0]][bombs[i][1]].getText().equals("X")) {
                bombs[i][0] = rand.nextInt(r);
                bombs[i][1] = rand.nextInt(c);
        }
            grid[bombs[i][0]][bombs[i][1]].setText("X");
        }
        //Creación y colocación de animats
        for (int i = 0; i < anis; i++) {
            Animat a = new Animat(r, c, grid);
            while (grid[a.getPosx()][a.getPosy()].getText().contains("@") || grid[a.getPosx()][a.getPosy()].getText().equals("X")) {
                a = new Animat(r, c, grid);
            }
            ani[i] = a;
            grid[a.getPosx()][a.getPosy()].setText(a.getNombre());
        }
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Buscabombas");
        setMinimumSize(new java.awt.Dimension(300, 350));
        setPreferredSize(new java.awt.Dimension(300, 350));
        setSize(new java.awt.Dimension(300, 350));

        jLabel1.setText("Movimientos:");

        jLabel2.setText("0");

        jButton1.setText("Siguiente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Bombas:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton1))
                .addContainerGap(265, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        for (Animat a : ani) {
            if (grid[a.getPosx()][a.getPosy()].getText().equals(a.getNombre()))
                grid[a.getPosx()][a.getPosy()].setText("");
            a.sexyMovimiento();
            if (grid[a.getPosx()][a.getPosy()].getText().equals("X")) {
                numbombs--;
                jLabel4.setText(numbombs + "");
            }
            grid[a.getPosx()][a.getPosy()].setText(a.getNombre());
        }
        tiempo--;
        tiem++;
        jLabel2.setText(tiem + "");
        //}
        if (numbombs == 0) {
            //gané
            JOptionPane.showMessageDialog(null, "¡Ganaste!", "Victoria", JOptionPane.YES_OPTION);
            System.exit(0);
        }
        else if (tiempo < 1) {
            //perdí
            JOptionPane.showMessageDialog(null, "¡Perdiste!", "Fracaso", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }   
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
